name: HydraJoinMsgs
version: '1.0'
main: vadlox.dev.hydraJoinMsgs.HydraJoinMsgs
api-version: '1.21'
description: The Ultimate Clans Plugin.
websites:
  - https://vadlox.hydraquest.net
  - https://github.com/vadlox
authors:
  - Vadlox
