name: HydraJoinMsgs
version: '1.0.2'
main: vadlox.dev.hydraJoinMsgs.HydraJoinMsgs
api-version: '1.21'
description: The Ultimate Clans Plugin.
depend:
  - PlaceholderAPI
websites:
  - https://vadlox.hydraquest.net
  - https://github.com/vadlox
authors:
  - Vadlox
commands:
  hydrajoinmsgs:
    description: Reloads the HydraJoinMsgs plugin configuration.
    usage: /<command> reload
    permission: hydrajoinmsgs.admin
permissions:
  hydrajoinmsgs.admin:
    description: Allows admins to reload the HydraJoinMsgs plugin.
    default: op

